### ISSUE TITLE
Finalize logo

### ISSUE THREAD

**Issue by adityasaky** [gittuf/community#5]
Leading logo candidates:

![image](https://github.com/gittuf/community/assets/8928778/54231b71-5be4-41de-aaf9-9ae92f57b4cf)
![image](https://github.com/gittuf/community/assets/8928778/ae221f55-f486-4650-883f-5772cb47896c)
![image](https://github.com/gittuf/community/assets/8928778/d3e7942c-6cb9-4087-a9df-e428eda50a25)

**Comment by JustinCappos** [comment]
I vote for 2.  But, let's just pick it and go!

**Comment by adityasaky** [comment]
I've put it on the agenda for this week's meeting: #4.

**Comment by hythloda** [comment]
<img width="783" alt="Screenshot 2024-01-05 at 12 16 23 PM" src="https://github.com/gittuf/community/assets/51727488/f2b35c79-9c13-4755-a36c-7ed68477539b">

**Comment by adityasaky** [comment]
In today's community meeting (#4), we decided on option 3 as the gittuf logo!

![image](https://github.com/gittuf/community/assets/8928778/d3e7942c-6cb9-4087-a9df-e428eda50a25)
